# Generated by Django 5.0.4 on 2024-04-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoIdentificacion', models.CharField(choices=[('Cedula', 'CEDULA'), ('NIT', 'NIT')], max_length=20)),
                ('fechaIngreso', models.DateField()),
                ('salarioMensual', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados_api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Celular', 'CELL'), ('Telefono', 'TEL')], max_length=20)),
                ('indicativo', models.CharField(max_length=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados_api.empleado')),
            ],
        ),
    ]
