# Generated by Django 5.0.4 on 2024-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='numero',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
